### ISSUE TITLE
does the Aqara E1 can be supported to RTSP ?

### ISSUE THREAD

**Issue by bmwcar** [niceboygithub/AqaraCamera#12]
https://www.aqara.com/en/product/camera-e1/
Dear Bro , this camera  how to get the RTSP or Onvif ? 
Thanks for your help !

**Comment by niceboygithub** [comment]
I don't have Camera E1. Wait for someone to donate.

**Comment by bmwcar** [comment]
how to donate ?

**Comment by bmwcar** [comment]
@niceboygithub  can i donate to you ? how to do it ?
