### ISSUE TITLE
last update broke integration

### ISSUE THREAD

**Issue by chepa92** [niceboygithub/AqaraCamera#2]
missing from integration list

**Comment by msth** [comment]
i can't find the integration in the repository
have tried both. Unfortunately without success

- If the integration didn't show up in the list please REFRESH the page
- If the integration is still not in the list, you need to clear the browser cache.

**Comment by HepoH3** [comment]
You need to add link of this repo into HACS->custom repos, then install custom integration, reboot HA core, go to the settings/Devices and services -> Add integration AqaraCamera
Did you do all of this?

**Comment by msth** [comment]
i have added the repo. 
![image](https://user-images.githubusercontent.com/1927680/151973493-1b6b92c6-d5a7-4e19-ba05-b601e886c648.png)
then reboot the core and the whole server
then nothing 
![image](https://user-images.githubusercontent.com/1927680/151975220-b0ba723a-24c6-4282-a0ae-b2c3152ed1d8.png)

**Comment by msth** [comment]
found my mistake. I had the repository installed but didn't install the integration via hacs. now it's working. sorry for the trouble
